import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c6c6c7",
        surface: "#131313",
        "surface-dim": "#131313",
        background: "#131313",
        "inverse-on-surface": "#313030",
        "tertiary-fixed-dim": "#9ccaff",
        "surface-tint": "#ffb693",
        "inverse-primary": "#a04100",
        "primary-fixed": "#ffdbcc",
        "surface-container-high": "#2a2a2a",
        "outline-variant": "#5a4136",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed-variant": "#00497b",
        "surface-variant": "#353534",
        "on-secondary-fixed-variant": "#454747",
        "on-secondary": "#2f3131",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#001d35",
        "on-surface": "#e5e2e1",
        "secondary-container": "#454747",
        primary: "#ffb693",
        "on-surface-variant": "#e2bfb0",
        "on-primary-container": "#572000",
        "on-secondary-fixed": "#1a1c1c",
        "surface-container-lowest": "#0e0e0e",
        secondary: "#c6c6c7",
        "tertiary-container": "#059eff",
        "secondary-fixed": "#e2e2e2",
        "on-primary": "#561f00",
        "surface-container": "#201f1f",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "tertiary-fixed": "#d0e4ff",
        "surface-bright": "#393939",
        "surface-container-highest": "#353534",
        "primary-container": "#ff6b00",
        "on-secondary-container": "#b4b5b5",
        "on-tertiary": "#003257",
        outline: "#a98a7d",
        "on-primary-fixed-variant": "#7a3000",
        tertiary: "#9ccaff",
        "surface-container-low": "#1c1b1b",
        "primary-fixed-dim": "#ffb693",
        "on-primary-fixed": "#351000",
        "on-tertiary-container": "#003357",
        // Accent palette (matches shader orbs)
        coral: "#FF5F4A",
        amber: "#F5A623",
        mint: "#34C98A",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        gutter: "16px",
        lg: "24px",
        margin: "24px",
        xl: "48px",
      },
      fontFamily: {
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "body-lg": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "label-caps": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "code-snippet": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "body-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-xl": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "body-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-lg": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "code-snippet": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;
